ALTER TABLE falcon.users ADD COLUMN IF NOT EXISTS must_change_password BOOLEAN NOT NULL DEFAULT FALSE;
     ALTER TABLE falcon.users ADD COLUMN IF NOT EXISTS is_verified BOOLEAN NOT NULL DEFAULT FALSE;
     ALTER TABLE falcon.users ADD COLUMN IF NOT EXISTS ban_reason VARCHAR(255);